resolver: lts-15.13
packages:
  - patchgirl-web/
  - patchgirl-runner/

extra-deps:
  - servant-flatten-0.2
  - servant-elm-0.7.2
  - http-client-0.7.2.1
  - http-conduit-2.3.7.3
  - dhall-1.36.0
  - repline-0.4.0.0
  - haskeline-0.8.1.0
  - atomic-write-0.2.0.7
  - prettyprinter-1.5.1
  - prometheus-metrics-ghc-1.0.0
  - wai-middleware-prometheus-1.0.0
  - strings-1.1
  - elm-bridge-0.6.1
  - servant-auth-client-0.4.0.0@sha256:2875edeb95854422b87188d8385c5cf04333afcb92d8643f3af2b3a4642bddb8,3426
  - hspec-hedgehog-0.0.1.2@sha256:4d09c7be34cdc941b78e4e964f71013ffeeb099ea32d8ede17ad9c03ae7a62e3,1470

nix:
  enable: true
  packages: [ postgresql, zlib ]

allow-newer: true