name: patchgirl-runner

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NamedFieldPuns
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - RecordWildCards
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - MultiWayIf
  - StrictData
  - TypeApplications # allows you to use visible type application in expressions, eg: show (read @Int "5")

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -Wincomplete-patterns
  - -Wcompat # make code future compatible to adapt to new features
  - -Wincomplete-record-updates # catch what are essentially partial pattern-matches
  #- -Wincomplete-uni-patterns
  - -Wredundant-constraints # help remove unnecessary typeclass constraints on functions
  - -fwrite-ide-info
  - -hiedir=.hie

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - servant-client
      - patchgirl-runner

library:
  source-dirs:
    - src

executables:
  patchgirl-runner-exe:
    source-dirs:
      - app
    main: Main.hs
    dependencies:
      - patchgirl-runner

dependencies:
  - patchgirl-web
  - base
  - wai-cors
  - scientific
  - text
  - vector
  - servant-server
  - utf8-string
  - dhall
  - aeson
  - unordered-containers
  - wai
  - warp
  - mtl
  - bytestring
  - uuid
  - lens
  - case-insensitive
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - say
  - containers
  - connection
  - wai-cors
  - wai-middleware-prometheus
  - prometheus-client
  - prometheus-metrics-ghc
  - stm
  - postgresql-libpq