name: patchgirl-web

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NamedFieldPuns
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - RecordWildCards
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeApplications # allows you to use visible type application in expressions, eg: show (read @Int "5")

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -Wincomplete-patterns
  - -Wcompat # make code future compatible to adapt to new features
  - -Wincomplete-record-updates # catch what are essentially partial pattern-matches
  #- -Wincomplete-uni-patterns
  - -Wredundant-constraints # help remove unnecessary typeclass constraints on functions


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - patchgirl-web
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

library:
  source-dirs:
    - src

executables:
  patchgirl-web-exe:
    main: app/Main.hs
    dependencies:
      - patchgirl-web

dependencies:
  - base
  - servant
  - servant-client
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-auth-client
  - servant-flatten
  - transformers
  - aeson
  - wai
  - warp
  - warp-tls
  - postgresql-simple
  - text
  - servant-elm
  - aeson-qq
  - unordered-containers
  - lens
  - mtl
  - case-insensitive
  - cookie
  - bytestring
  - utf8-string
  - email-validate
  - dhall
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - time
  - jose
  - wai-middleware-prometheus
  - prometheus-client
  - prometheus-metrics-ghc
  - uuid
  - strings
  - control-monad-free
  - monad-loops
  - say
  - stm
  - containers
  - connection
  - wai-cors
